fechatupla1 = ( 25 , 12 , 2016 )
print ( "Imprimimos la primera tupla" )
imprimir ( fechatupla1 )
fechalista = lista ( fechatupla1 )
print ( "Imprimimos la lista que se le copio la tupla anterior" )
imprimir ( fechalista )
fechalista [ 0 ] = 31
print ( "Imprimimos la lista ya modificada" )
imprimir ( fechalista )
fechatupla2 = tupla ( fechalista )
print ( "Imprimimos la segunda tupla que se le copio la lista" )
imprimir ( fechatupla2 )
