tupla = ( 1 , 2 , 3 )
fecha = ( 25 , "Diciembre" , 2016 )
punto = ( 10 , 2 )
persona = ( "Rodríguez" , "Pablo" , 43 )
imprimir ( tupla )
imprimir ( fecha )
imprimir ( punto )
imprimir ( personaje )
